### ISSUE TITLE
EnchantmentGlow v1_18_R2

### ISSUE THREAD

**Issue by VSpier** [hakan-krgn/hCore#24]
error - ![Screenshot from 2022-06-13 02-03-34](https://user-images.githubusercontent.com/18331908/173257325-2fb56a63-42da-4847-b3cf-2ea866c3e45a.png)
if make abstract ![Screenshot from 2022-06-13 02-05-06](https://user-images.githubusercontent.com/18331908/173257331-185238f0-6a4a-4cae-adb7-abefdf142dcc.png)

**Comment by osmanfurkan115** [comment]
hCore depends on spigot, not paper. Therefore, Enchantment#displayName, which is an abstract method on paper api, won't be implemented.
