### ISSUE TITLE
[Suggestion] Add async (packets-based) scoreboards

### ISSUE THREAD

**Issue by BlackBaroness** [hakan-krgn/hCore#28]
Hi! Scoreboard api looks cool, but how about async update support?

There are working packets-based solutions (like [this](https://github.com/MrMicky-FR/FastBoard)), so this is not something hard. Async scoreboards api would allow developers to create heavy calculation scoreboards during update (because there might be queries to the database, etc.). 

This API can be called both synchronously and asynchronously because packets work the same way.

I think that `ForkJoinPool` would be perfect for these purposes.

**Comment by hakan-krgn** [comment]
Actually, I wanted to add async scoreboard system but I didn't prefer using packets because Spigot offers a stable API. I'll add this feature in the next version. Thanks for suggestion!

**Comment by BlackBaroness** [comment]
There are some more tips: instead of `int` + `TimeUnit`, it is more beautiful and more convenient to use `Duration`. Wherever ticks are specified as a unit of time, `Duration` support will also be useful (for example, I want to update the scoreboard every second, in which case `.expire(Duration.ofSeconds(1))` will be prettier than `.expire(20)`).

I don't know where to discuss such minor edits, creating an issue for this seems to me something stupid. Maybe I'll make a pull request with some improvements like this.

**Comment by hakan-krgn** [comment]
Okay, I think it's finished (https://github.com/hakan-krgn/hCore/commit/d2735444fe503937d21667fd73174b3155bfb9c2)
