### ISSUE TITLE
[Suggestion] Getting spam remaining time from HCore.spam(id, cooldown)

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#32]
Example:
HCore.spam(id, cooldown) will return remaining time

**Comment by hakan-krgn** [comment]
Hi! Actually HCore.spam(id, cooldown) returns boolean. But If you want I can add HCore.spam(id) to return remain time?

**Comment by zhogoshi** [comment]
yes.
u can also do something like:
HCore.spam(id, time, TimeUnit/Duration)
and it will return remaining time but it will be returned in provided time unit or duration, example:
HCore.spam("id", 2, TimeUnit.SECONDS)
after 0.5 seconds for example it will return 1.5, or after. 2 seconds it will return 0, so, it means that remaining time end
or:
HCore("id", 15, TimeUnit.MINUTES)
and it will return remaining time in hours, like after 5 minutes it will return
10

**Comment by hakan-krgn** [comment]
This should work for you. (https://github.com/hakan-krgn/hCore/commit/f901db095d8191d83c45bceeb53124fe64d6d72a)
