### ISSUE TITLE
[Suggestion] Add NPC command

### ISSUE THREAD

**Issue by oer2349** [hakan-krgn/hCore#33]
Can you bring command adding support for NPCs? the command execution features of most npc plugins like citizens are very bad.

**Comment by zhogoshi** [comment]
~~hCore is plugin for working with npcs~~ **hCore is multi-functional developer tool for spigot developers.**

there is no need to add this command, this lib proivides alot of cool features only for devs. citizens is a library which allows you to create npcs with commands, and it has api which allows do the same things what can commands.

how bout other plugins, not only citizens?

**Comment by hakan-krgn** [comment]
That's right, hCore is not an plugin, it's an tool for spigot developers. Also If you are a developer, you can use .whenClicked() method to run a command.

**Comment by oer2349** [comment]
More than 200 people are using npc on my server at the same time, so I asked if you could add a more optimized npc-command system because when I use any npc-plugin, the plugin always consumes high cpu if you can add a command system to hCore, I can develop it from this api.

**Comment by zhogoshi** [comment]
just do itself. as i said, hCore isnt plugin for working with npcs.

also, command system already exists in hCore
[click here](https://github.com/hakan-krgn/hCore/wiki/AnnotationCommand)
