### ISSUE TITLE
[Suggestion] Particle enum for particle system

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#34]
``HParticle myParticle = new HParticle("HEART", 30, 0.2, new Vector(0.3, 0.3, 0.3); // creates a new HParticle which uses "HEART" particle as template
HCore.playParticle(player, player.getLocation(), myParticle); // plays the particle at player's location``

how bout creating enum like HCoreParticle, like:

enum HCoreParticle {
HEART;
}

then, it may look like
``HParticle myParticle = new HParticle(HCoreParticle.HEART, 30, 0.2, new Vector(0.3, 0.3, 0.3); // creates a new HParticle which uses "HEART" particle as template
HCore.playParticle(player, player.getLocation(), myParticle); // plays the particle at player's location``

prob im clown coz ill just able to use org.bukkit.Particle.HEART.name, but anyways, it prob will be better? <3

**Comment by hakan-krgn** [comment]
Okay, I will add this feature in the next version, thanks for suggestion.

**Comment by hakan-krgn** [comment]
Finished. (https://github.com/hakan-krgn/hCore/commit/f515c53050ea379b7dd5f41143e5352764ff7409)
