### ISSUE TITLE
[Suggestion] Better args for command system

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#35]
while i was making commands i ran into one problem - to make a command that contains an argument with a hint in the form of player nicknames / similar things, so idk how it should look, cos cmd system should be fully rewritten

example:
// so, how to do this?
/tp playername

probably it will be better if someone can rewrite this system, and it should looks like this:

kotlin:
val subCmd = SubCMD()

@SubCommand
fun tpCommand(sender: CommandSender, args: Array<String>) : SubCMD {
if(args.isEmpty || sender !is Player) return

for(player in Bukkit.getOnlinePlayers()) {
subCmd.args[0]/*(it can be as list<String>, not only string)*/.add(player.name)
}

val target = Bukkit.getOfflinePlayer(args[0]) ?: return // player isnt found
if(!Bukkit.getOfflinePlayer(args[0]).isOnline) return // Player isnt online

(sender as Player).teleport(target.location)

return subCmd
}

java:
SubCMD subCmd = new SubCmd();

@SubCommand
void tpCommand(CommandSender sender, List<String> args) {
if(args.isEmpty() || !(sender instanceof Player)) return;

for(Player player : Bukkit.getOnlinePlayers()) {
subCmd.args[0].add(player.name);
}

OfflinePlayer target = Bukkit.getOfflinePlayer(args[0]);
assert target != null;

((Player)sender).teleport(target.getLocation());
return subCmd;
}

i wanna send alot of suggestions coz i have alot of ideas so i didnt wanted to submit this, anyway, why not? :p 
i'll love guy whose will do this, because theres one problem: idk how it should look with annotations, so, i cant help there ;(
also, im sorry for bad code cos i wrote this in gh xdf
fuk gh i cant even somehow highlite code ;(

**Comment by hakan-krgn** [comment]
I will try to add <player> argument placeholder for getting list of players in tab completion.

**Comment by hakan-krgn** [comment]
https://github.com/hakan-krgn/hCore/commit/0eaa121d88039714b0424124c8208f6bc74dd487
Okay, finished.
