### ISSUE TITLE
[Suggestion] Autolook for npcs

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#37]
how bout add property to HNPC which will allow npc look to player? i mean, npc will look on player in provided radius.

also, how bout do it locally? i mean, if 2 players will stay near npc
1st player will see that npc looks on him
2nd player will see that npc looks on him, with every player this thing
also, how bout add method .lookTo(Player p) or .lookTo(Location loc)?

**Comment by hakan-krgn** [comment]
finished > https://github.com/hakan-krgn/hCore/commit/ff3e2ef272c3dff238751d5b38955e6d5bd70259
