### ISSUE TITLE
[bug] NPCs

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#38]
if i create npc in onEnable method, setskin and setlocation, then .showEveryone(true) him i'll set this thing:
![image](https://user-images.githubusercontent.com/85288982/179344848-09b5509b-1e57-4a72-968f-de423c692a6d.png)
npc have no skin and have glitched head rotation :( but if ill just set skin, head rotations will be good aswell skin will be shown, after rejoining on server im getting the same effect.

**Comment by hakan-krgn** [comment]
I will check it

**Comment by hakan-krgn** [comment]
Fixed -> https://github.com/hakan-krgn/hCore/commit/6717493dc0f0b830825a7f1f7f625cc16fbeeb01
Also you should store HNpcSkin value before using the HNPC#setSkin method

**Comment by zhogoshi** [comment]
problem still exists :(

**Comment by hakan-krgn** [comment]
Load HNpcSkin when the player join the server or below the onLoad then store it in variable.
