### ISSUE TITLE
[Suggestion] Scoreboard system

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#41]
add to HScoreboard method which will return org.bukkit.scoreboard, so it can be like:

player.setScoreboard(hboard.getScoreboard())

someone will be able to create alot of hscoreboards and easily switching them.
also big plus to this: player1.setScoreboard() player2.. i mean, add to specified players scoreboard.
example:

HScoreboard welcomeBoard = HScoreboard.create()
HScoreboard hiBoard = HScoreboard.create()
// add some fields to boards
if(player.isFirstJoin) {
player.setScoreboard(welcomeBoard.getScoreboard())
} else {
player.setScoreboard(hiBoard.getScoreboard())
}

**Comment by hakan-krgn** [comment]
In fact, we cannot do this with the current system. Because I don't store any value related to scoreboard. Everything works via packets.
