### ISSUE TITLE
[Bug] npcs look

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#48]
after unloading npc (when player far from npc, npc unloads and when he isnt far from npc, npc loads) and loading npc yaw and pitch will be set to 0 for some reason
![image](https://user-images.githubusercontent.com/85288982/181902724-92013683-2a50-419e-8b3c-9718dcbc6c6a.png)

**Comment by hakan-krgn** [comment]
Fixed https://github.com/hakan-krgn/hCore/commit/e70eaef155aafa9f11c4e75c0ee7b2aff922c6ee
