### ISSUE TITLE
[Suggestion] Hologram clicks

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#49]
so, hb do something like chaning range of interaction with holo?

**Comment by hakan-krgn** [comment]
I couldn't understand, what did you mean with "hb"?

**Comment by zhogoshi** [comment]
hb - how bout?

**Comment by zhogoshi** [comment]
why not using this way?:

detect playerinteractevent, check if it is left/right click air
then using for loop check if someone exists in provided range using player direction, if it is, check if its holo. prob done, then just u know that player clicked on holo with provided range.

and check if player didnt interacted with holo in default range (3 blocks) (it will fix problem that if u will interact with holo by default range, it will think that u clicked 2 times)

**Comment by hakan-krgn** [comment]
We cannot check right click air with empty hand so we needs extra hologram
