### ISSUE TITLE
[Command] Placeholder problem

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#50]
alr i figured out one placeholder's problem. anyway, idk how this problem works :( i mean, why this happens**

code: 
kotlin : https://hastebin.com/kibebelowi.kotlin
java : https://hastebin.com/pizonodabe.kotlin

problem:  
![image](https://user-images.githubusercontent.com/85288982/182329995-7d507615-4b0d-4e18-868f-4dd00e767bea.png)

(WARN) this problem works on both langs, java and kotlin, i tried it. anyway, java result (probably with every server load random placeholder works):
![image](https://user-images.githubusercontent.com/85288982/182331525-86377aa4-255d-41a0-ade5-818551d07b15.png)

anyway, in other situations placeholders works perfectly.

UPD. i checked if will something better using +1 arg like: 
![image](https://user-images.githubusercontent.com/85288982/182332880-de922f14-66ea-480a-9f2d-96340387c784.png)

but, nothing...

**Comment by hakan-krgn** [comment]
```java
@BaseCommand(
        name = "gamemode",
        usage = "/gamemode",
        aliases = {"gm"}
)
public class Test {

    @SubCommand(args = {"<%mode%>"})
    public void gamemodeSurvival(CommandSender sender, String[] args) {
        String mode = args[0];
        System.out.println(mode);
    }

    @Placeholder(name = "mode")
    public List<String> survivalPlaceholders() {
        return Arrays.asList("0", "1", "2", "3", "survival", "creative", "adventure", "spectator");
    }
}
```

use like this.
