### ISSUE TITLE
[bug] npc skin

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#51]
probably its my problem, like, im storing skin bad
![image](https://user-images.githubusercontent.com/85288982/182657248-3c7c69fc-1696-4431-ab4d-eb0d848624ac.png)
, but, anyway:

i set npc's skin to one guy. but, skin doesnt shows when i joined on server (i mean like first join after enabling server)
but, if ill rejoin to server, all be k

also sometimes it shows properly, sometimes no (uh???)

anyway, im storing npc's skin before setSkin method, so, idk why this h4ppens

storing:
val skin = HNpcSkin.from(if(skinOfPlayer) player.name else skin) // in both situations there will be mine name for me, i checked it

**Comment by hakan-krgn** [comment]
If you need to set skin immediately after load the skin, try to wait a tick to use HNPC#setSkin
