### ISSUE TITLE
[Suggestion] placeholder improvement

### ISSUE THREAD

**Issue by zhogoshi** [hakan-krgn/hCore#52]
how about adding perm to placeholder, or add placeholder only for specified player? (probably it will fix using in subcommand permission

for example:

i did admin command: /gm 1, and i dont want that players which cant use cmd can see this placeholder

how bout add to @Placeholder property "permission"? or specified players?

**Comment by hakan-krgn** [comment]
Finished https://github.com/hakan-krgn/hCore/commit/f9e2be433e3cc1e0dc92b17768269aa43cd2a1e0
