### ISSUE TITLE
[Suggestion] Setting NPC Skin via Texture & Signature

### ISSUE THREAD

**Issue by darknessNBK** [hakan-krgn/hCore#55]
It would be awesome if we could set the skin of the NPC via custom texture & signature values.

**Comment by hakan-krgn** [comment]
Hi, you can do it easily
```java
HNpcSkin skin = new HNpcSkin(texture, signature);
npc.setSkin(skin);
```

**Comment by darknessNBK** [comment]
I missed that in Javadocs I guess, thanks! _(adamsın.)_
