### ISSUE TITLE
[Bug] hCore v0.6.9.5 generated an exception

### ISSUE THREAD

**Issue by IamTheDefender** [hakan-krgn/hCore#65]
Using latest version of the plugin and here is the logs, https://drive.google.com/file/d/1SHqStkQcmgCeaHQ9FfflKPK76MLEQcqF/view 

I hope you would be able to help! have a good day

**Comment by hakan-krgn** [comment]
Hello, I couldn't see the line of the error. Could you please send me more clear log file?
